### ISSUE TITLE
Parameter 'driver' does not exist in report!

### ISSUE THREAD

**Issue by eshwarallaka** [lavela/phpjasper#14]
Hi,

Thank you for your package, I'm getting an error like **Parameter 'driver' does not exist in report!**  while typing command to generate the file.

Following is my command

jasperstarter process "E:\xampp\htdocs\pms\public/test.jasper" -o "E:\xampp\htdocs\pms\public/report/1465291497_codelution" -f pdf rtf -P driver="mysql" username="root" password="" host="localhost" database="test1"

Thank you.

**Comment by eshwarallaka** [comment]
Sorry,It's working well

it's totally my mistake. anyway thanks for your awesome package.

Thank you.

**Comment by tursunbaevz** [comment]
how you solved that?
