### ISSUE TITLE
Use on Laravel 5.6 - Call to undefined method

### ISSUE THREAD

**Issue by adalgdev** [lavela/phpjasper#33]
Hi. I can't add to Laravel 5.6 ( composer require lavela/phpjasper )

I get this:

`
[Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Foundation\Application::share()  
`

**Comment by TalesSathler** [comment]
Try: vendor/lavela/phpjasper/src/JasperPHP/JasperPHPServiceProvider.php:16

//        $this->app['jasperphp'] = $this->app->share(function()
//        {
//            return new JasperPHP;
//        });

        $this->app->singleton('jasperphp', function ($app) {
            return new JasperPHP;
        });
