### ISSUE TITLE
Issue for send multiple data in params parameter

### ISSUE THREAD

**Issue by jazi3652** [lavela/phpjasper#42]
I am facing issue when i am sending multiple data like send array in params parameter then i am facing the issue check this issue .
![Capture](https://user-images.githubusercontent.com/52414443/61389951-4888c700-a8d3-11e9-97b0-03f711d5cf4f.PNG)

**Comment by caioviniciusrodrigues** [comment]
Estou com os mesos problemas com essa biblioteca, dificil achar solução. Estou usando o Laravel 5.8
