### ISSUE TITLE
Data from json file

### ISSUE THREAD

**Issue by edukmattos** [lavela/phpjasper#6]
Very nice package ! Congratulations !
I have a problem with data from json file.
Im use tibco jasper studio.
In tests, its works but run in laravel the report dont show the data just only fields with null.

My controller:

public function report(Request $request)
    {
        $srch_code                       = $request->get('code');
        $srch_cpf                        = $request->get('cpf');
        $srch_name                       = $request->get('name');
        $srch_plan_id                    = $request->get('plan_id');
        $srch_gender_id                  = $request->get('gender_id');
        $srch_region_id                  = $request->get('region_id');
        $srch_city_id                    = $request->get('city_id');
        $srch_member_status_id           = $request->get('status_id');
        $srch_member_status_reason_id    = $request->get('status_reason_id');

```
    $members = $this->memberRepository->searchMembers($srch_code, $srch_cpf, $srch_name, $srch_plan_id, $srch_gender_id, $srch_region_id, $srch_city_id, $srch_member_status_id, $srch_member_status_reason_id);

    $content = $members->toJson();

    $file = public_path() . '/reports/members/search_results.json';

    File::delete($file);
    File::put($file, $content);

    $output = public_path() . '/reports/members/search_results_'.date("Ymd_His");

    $ext = "pdf";

    $report = new JasperPHP;
    $report->process
        (
            public_path() . '/reports/members/search_results.jrxml', 
            $output, 
            array('pdf')
        )->execute();

    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename=members_search_results_'.date("Ymd_His").'.'.$ext);
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    header('Content-Length: ' . filesize($output.'.'.$ext));
    flush();
    readfile($output.'.'.$ext);
    unlink($output.'.'.$ext);
}
```

Where Im missing ?

**Comment by geekcom** [comment]
Unfortunately it is not possible to use JSON as a data source , this is due to a restriction in jasperstarter library, which is a dependency for our library , for more information contact .
http://jasperstarter.cenote.de/

Skype ID: **leandro.bittencourt16**

**Comment by edukmattos** [comment]
Hi !
Is there any way to pass the sql for the .xml file? 
I need to spend a dynamic sql where there may be one or several conditions ( "where" ) .
I've tried to create a variable ( $ { P } variavle ) type text included in the where the sql but it worked .
What is your suggestion ?

**Comment by geekcom** [comment]
I unaware a way to convert a file . sql in an .xml type , however you can file you import that file using a DBMS , and then create a query returning an xml.

**Comment by edukmattos** [comment]
It works with files type csv ?

**Comment by geekcom** [comment]
yes it works

**Comment by edukmattos** [comment]
good ! i will try !
Anything I can ask for help you ?

**Comment by edukmattos** [comment]
good ! i will try !
Anything I can ask for your help ?

**Comment by geekcom** [comment]
Olá @ecmattos, tive uma solução para o seu problema, a função **process** aceita parâmetros via array, observe abaixo:

<pre>
`\JasperPHP::process(
            public_path() . '/report/teste.jasper', 
            $output, 
            array($ext), //o tipo de arquivo 'pdf'....
            array('teste' => '0121321', 'filtro' => $filtro), //você pode usar esse array para passar seu .json
            array(),  //aqui a conexão com o banco de dados                   
            false,
            false
        )->execute();`
</pre>

Espero que isso ajude.

**Comment by geekcom** [comment]
Hello @ecmattos , i had a solution to your problem , the **process function** accepts parameters via array , look below:

<pre>
`\JasperPHP::process(
            public_path() . '/report/teste.jasper', 
            $output, 
            array($ext), //o tipo de arquivo 'pdf'....
            array('teste' => '0121321', 'filtro' => $filtro), //você pode usar esse array para passar seu .json
            array(),  //aqui a conexão com o banco de dados                   
            false,
            false
        )->execute();`
</pre>

I hope this helps.

**Comment by edukmattos** [comment]
Oi !
Estou passando as variaveis via get:
http://localhost:8000/dashboard/reports?model=allMembersByPlanRegionStatus&plan_id=1&region_id=5&status_id=2

Está dando o seguinte erro:
Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.

Verificando no console do laravel, o erro é o seguinte:

Parameter 'jsp_plan_id' of type 'java.lang.Integer caused java.lang.NumberFormatException For input string: "1 jsp_region_id=3 jsp_member_status_id=2 "

Informa que estou passando "textos" ao inves de numeros para a variavel jsp_plan_id definida como integer.

Verificando se estou passando corretamente os valores, apliquei um dd($conditions), e os valores são passados de maneira certa:

No meu controller:
   $rpt_model                       = $request->get('model');
   $srch_plan_id                    = $request->get('plan_id');
   $srch_region_id                  = $request->get('region_id');
   $srch_member_status_id           = $request->get('status_id');

 if($rpt_model=='allMembersByPlanRegionStatus')
        {
          $conditions = array("jsp_plan_id"=>$srch_plan_id, "jsp_region_id"=>$srch_region_id, "jsp_member_status_id"=>$srch_member_status_id);
}
dd($conditions);

Resultado abaixo ok:
array:3 [▼
  "jsp_plan_id" => "1"
  "jsp_region_id" => "5"
  "jsp_member_status_id" => "2"
]

Nao sei o motivo por qual está considerando os valores das variaves como texto.

Mesmo passado somente uma variavel, ele considera como texto:

Parameter 'jsp_member_status_id' of type 'java.lang.Integer caused java.lang.NumberFormatException For input string: "2 "

Qual sera o meu erro ?

**Comment by edukmattos** [comment]
Esqueci de enviar o comando para executar:

$report = new JasperPHP;
        $report->process
        (
            $input, 
            $output, 
            array('pdf'),
            $conditions,
            $database  
        )->execute();

**Comment by edukmattos** [comment]
Alguma idéia  de onde estou errando ?

**Comment by edukmattos** [comment]
Descobri o problema !

Alterei as linhas 101 e 102 do arquivo /vendor/lavela/phpjasper/src/JasperPHP/JasperPHP.php

if( count($parameters) > 0 )
        {
            $command .= ' -P ';
            foreach ($parameters as $key => $value)
            {
101     $param = $key . '=' . $value . ''; /aspas final sem espaço
102          $command .= " \"$param\""; /adicionado um espaco simples apos a primeira aspas dupla
            }
        }

**Comment by edukmattos** [comment]
A nova versao 1.3, deu pau !
Congelei na versao 1.2 com as alteracoes acima.
